#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xsetroot -cursor_name left_ptr &
xinput --set-prop 9 'libinput Accel Speed' -1
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144 &
feh --bg-scale ~/.wallpaper.* &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a feh state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
